gnodeb:
  controlif:
    ip: "10.216.0.52"
    port: 9487
  dataif:
    ip: "10.216.0.52"
    port: 2152
  plmnlist:
    mcc: "208"
    mnc: "93"
    tac: "000001"
    gnbid: "000008"
  slicesupportlist:
    sst: "01"
    sd: "010203" # optional, can be removed if not used
  k: 1.5

ue:
  msin: "0000000001"
  key: "8baf473f2f8fd09487cccbd7097c6862"
  opc: "8e27b6af0e692e750f32667a3b14605d"
  amf: "8000"
  sqn: "00000000015b"
  dnn: "internet"
  routingindicator: "0000"
  hplmn:
    mcc: "208"
    mnc: "93"
  snssai:
    sst: 01
    sd: "010203" # optional, can be removed if not used
  integrity:
    nia0: false
    nia1: false
    nia2: true
    nia3: false
  ciphering:
    nea0: true
    nea1: false
    nea2: true
    nea3: false
amfif:
  - ip: "10.216.0.50"
    port: 38412
  - ip: "10.216.0.51"
    port: 38412
  - ip: "10.100.50.200"
    port: 38412
  - ip: "10.100.50.201"
    port: 38412
  - ip: "10.100.50.202"
    port: 38412
  - ip: "10.100.50.203"
    port: 38412
  - ip: "10.100.50.204"
    port: 38412
  - ip: "10.100.50.205"
    port: 38412
  - ip: "10.100.50.206"
    port: 38412
  - ip: "10.100.50.207"
    port: 38412
logs:
    level: 7
test: 
  printTimeStamp: true
  periodicPDUSessionCreateDestroy: true